---
title: "Acknowledgements and Links"
output: html_document
---

### My lecturers Andy MacLachlan and Adam Dennett

Both of them have been nothing short of wonderfully helpful in patiently explaining problems and going through bugs in my R code with me (a particularly nightmarish one included a space in a folder name causing my data to be unreadable!). A mighty challenge to impart GIS skills in such a short span of time indeed! While I have taken some code from their detailed practicals [here](https://andrewmaclachlan.github.io/CASA0005repo/index.html), all shortcomings and mistakes in this piece of work are mine alone.

### Matthew Crump 

His very informative guide on how to publish an R Markdown Website on Github Pages came in super handy for me [here](https://www.youtube.com/watch?v=nc7XhQrasCM&t=250s). I published this webpage with the help of files forked from his [repository](https://github.com/CrumpLab/LabJournalWebsite). Have a look to see how you can create your very own R Markdown Website too! 

### Emily Burchfield

Her detailed site on point pattern analysis, and especially on the G and F functions, were very enlightening for my learning and research purposes. Great analysis and very accessible content - check it out [here](https://eburchfield.github.io/files/Point_pattern_LAB.html).

### Mark Burkey

His informative and step-by-step video on different spatial regression models was great! Worthy of mention was how there was a .txt file of code for the Lagrange Multiplier Tests, and how it was clearly explained. I learnt so much about the implementation of different spatial regression models from his efforts! If you're looking for information on Spatially Lagged X models, Spatial Lag Models, or Spatial Error Models in R - [here](https://www.youtube.com/watch?v=b3HtV2Mhmvk&t=2041s) is the place.

### My report/write-up
 
You can find my completed report in my Github repository named "Report.pdf", but I will link it [here](https://github.com/tsin95/CASA0005GISProj/blob/master/Report.pdf) again.


